name: Android CI

on:
  pull_request:
  release:
    types: [published]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: set up JDK
      uses: actions/setup-java@v4
      with:
        java-version: '21.0.5'
        distribution: 'jetbrains'
        cache: gradle

    - name: Grant execute permission for gradlew
      run: chmod +x gradlew
    - name: Build with Gradle
      run: ./gradlew assembleDebug

    - uses: actions/upload-artifact@v4
      with:
        name: my-artifact
        path: app/build/outputs/apk/debug/Filament_Manager-*-*.apk
